POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZG9AZXhhbXBsZS5pbyIsImV4cCI6MTc3ODI5NjA2NywidXNlcklkIjoyfQ._yeALK2-CFN1B8zb9gFz-m7jIOHn0p-TAxUHYkTcBUM

{
  "name": "Javascript",
  "description": "JS events",
  "location": "Cirebon",
  "datetime": "2026-05-09T15:30:00.000Z"
}